### ISSUE TITLE
[Bug]: TestForm app: KCombobox from main.cs causes a crash when theme is MS Office 365 Blue

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1462]
**Describe the bug**
Main.cs (form Main) contains a KCombobox. 

**To Reproduce**
1. Create a test branch from alpha and switch to it.
2. add a button to startscreen that lauches main(.cs) form
3. Build and run

**Expected behavior**
When the theme is Office365 Blue it produces an exception.
Change the theme to something else and it works.
All other forms launched from startscreen have no issues

**Desktop (please complete the following information):**
 - OS: Win!!
 - Brach from Alpha for testing this
 - Frameworks tested: 4.8 / 6.0
 
**Additional context**
Is most probably related to the current work on warnings.

**Comment by giduac** [comment]
@Wagnerp 
Please, assign to Giduac.

TY!

**Comment by Wagnerp** [comment]
> @Wagnerp Please, assign to Giduac.
> 
> TY!

@giduac 

Done! :)

**Comment by giduac** [comment]
@Wagnerp 

A question about this and maybe you can help me short circuit this.

The error happens when the main form is shown and the Office 365 blue theme is active.
When for example the Office 365 Dark theme is active all is good.
When the font type and size is changed in StateCommon.Content in the designer the error is gone.

Could you please have a look if there are differences between the Blue and Dark theme which could lead to this?

**Comment by giduac** [comment]
> > @Wagnerp
> The only differences I can think of are the colours. You could use a application called WinMerge to compare the differences.

if a font is selected/set here then the errror is gone. Remove the font and the error is back.

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/da90987d-6419-48b7-b141-223ce6b689ff)

**Comment by giduac** [comment]
@Smurf-IV 
Can you please spare a couple of minutes and have a look at the topic start and the findings so far to see if you can point us in right direction here.

**Comment by Smurf-IV** [comment]
@giduac FYI: I have other things scheduled - I'll not be able to get to this until the 26th of May at the earliest.

**Comment by giduac** [comment]
> @giduac FYI: I have other things scheduled - I'll not be able to get to this until the 26th of May at the earliest.

OK, NP.

I'll see how far I can get on this in the mean time.

**Comment by giduac** [comment]
@Smurf-IV & @Wagnerp 
Narrowed down further. Topic start updated.

**Comment by Smurf-IV** [comment]
@giduac are you in a position to solve this, Or do you want me to "have a go" at it still ?

**Comment by giduac** [comment]
Hi @Smurf-IV ,
I'd like you to have a look at it and see what you can make of it.
Not sure if I got all the info that's to be had.
This ain't cut and dried, and could well be an error within dotnet itself.

The topic start shows how far i got.
And main.cs is Testform still has this error.

Keep me posted on your findings and I'll see if I can be of assistance...

**Comment by giduac** [comment]
@Smurf-IV 
FYI: Corrected the title and added to the topic start:
*- Added: as stated earlier, it is not related to a specific theme.*

**Comment by giduac** [comment]
@Smurf-IV 
Tested this on alpha and the error is gone!
